name: flutter_application_m3awda
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  http: 1.3.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  path_provider: ^2.1.2  
  flutter_native_splash: ^2.3.10
  get: ^4.6.6
  flutter_otp_text_field: ^1.1.1
  get_storage: ^2.1.1
  url_launcher: ^6.0.3
  google_maps_flutter: ^2.2.0
  dio: ^4.0.6
  flutter_polyline_points: 2.1.0
  flutter_svg: ^2.0.17
  shared_preferences: ^2.0.15
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  line_awesome_flutter: ^2.0.0
  cloud_firestore: 5.6.6
  intl: ^0.19.0
  image_picker: ^1.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#f7f6f1"
  image: assets/images/logo.png
  color_dark: "#272727"
  image_dark: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#272727"

  web: false
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/welc.png
    - assets/images/welcome_images/welcome.png
    - assets/logo/g_logo.png
    - assets/images/forget_password/password.png
