// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcYsm9gSs-3rfF94ZEx77nf6k8Hnp7oQ8',
    appId: '1:571551533992:web:4017e61a55de008fc5eb9d',
    messagingSenderId: '571551533992',
    projectId: 'flutter-login-app-82fd7',
    authDomain: 'flutter-login-app-82fd7.firebaseapp.com',
    storageBucket: 'flutter-login-app-82fd7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHkofT36a8ehI9GQqvimj2ibDX-pWkjBU',
    appId: '1:571551533992:android:da30431edd2dc8ccc5eb9d',
    messagingSenderId: '571551533992',
    projectId: 'flutter-login-app-82fd7',
    storageBucket: 'flutter-login-app-82fd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4KCjceudJTkK0Az_5ChB_BO-35gK6fcw',
    appId: '1:571551533992:ios:ad03af210e1dfbf6c5eb9d',
    messagingSenderId: '571551533992',
    projectId: 'flutter-login-app-82fd7',
    storageBucket: 'flutter-login-app-82fd7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationM3awda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4KCjceudJTkK0Az_5ChB_BO-35gK6fcw',
    appId: '1:571551533992:ios:ad03af210e1dfbf6c5eb9d',
    messagingSenderId: '571551533992',
    projectId: 'flutter-login-app-82fd7',
    storageBucket: 'flutter-login-app-82fd7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationM3awda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcYsm9gSs-3rfF94ZEx77nf6k8Hnp7oQ8',
    appId: '1:571551533992:web:009348c3885621cec5eb9d',
    messagingSenderId: '571551533992',
    projectId: 'flutter-login-app-82fd7',
    authDomain: 'flutter-login-app-82fd7.firebaseapp.com',
    storageBucket: 'flutter-login-app-82fd7.firebasestorage.app',
  );
}
